### ISSUE TITLE
Easy installation with py2exe / PyInstaller

### ISSUE THREAD

**Issue by quasar098** [Ookamiko/SnakePy#2]
PyInstaller and py2exe would be better as it would allow for easy playing during releases.
It might be a little excessive for a first project but it counts i guess.

**Comment by Ookamiko** [comment]
That's not a bad idea. I will think about it for the next release but I must admit that this project is mainly to develop an other one so it was not really attended to be played. And I don't think people will turn to this project to play snake 😄 
But, yeah, if I make a portfolio surely I will use an installer for people to use it easely.

**Comment by Ookamiko** [comment]
Well, I add pyinstaller. Thanks for the improvement 😉
